comparable_user_attributes = {
    "first_compare": ["User", "Host"],
    "second_compare": [
        "plugin",
        "authentication_string",
        "password_expired",
        "password_lifetime",
        "account_locked",
        "Create_role_priv",
        "Drop_role_priv",
        "Password_reuse_history",
        "Password_reuse_time",
        "Password_require_current",
        "User_attributes",
        "ssl_type",
        "ssl_cipher",
        "x509_issuer",
        "x509_subject",
        "Select_priv",
        "Insert_priv",
        "Update_priv",
        "Delete_priv",
        "Create_priv",
        "Drop_priv",
        "Reload_priv",
        "Shutdown_priv",
        "Process_priv",
        "File_priv",
        "Grant_priv",
        "References_priv",
        "Index_priv",
        "Alter_priv",
        "Show_db_priv",
        "Super_priv",
        "Create_tmp_table_priv",
        "Lock_tables_priv",
        "Execute_priv",
        "Repl_slave_priv",
        "Repl_client_priv",
        "Create_view_priv",
        "Show_view_priv",
        "Create_routine_priv",
        "Alter_routine_priv",
        "Create_user_priv",
        "Event_priv",
        "Trigger_priv",
        "Create_tablespace_priv",
        "max_questions",
        "max_updates",
        "max_connections",
        "max_user_connections",
    ],
}

comparable_db_attributes = {
    "first_compare": ["User", "Host", "Db"],
    "second_compare": [
        "Select_priv",
        "Insert_priv",
        "Update_priv",
        "Delete_priv",
        "Create_priv",
        "Drop_priv",
        "Grant_priv",
        "References_priv",
        "Index_priv",
        "Alter_priv",
        "Create_tmp_table_priv",
        "Lock_tables_priv",
        "Create_view_priv",
        "Show_view_priv",
        "Create_routine_priv",
        "Alter_routine_priv",
        "Execute_priv",
        "Event_priv",
        "Trigger_priv",
    ],
}
